; # x-coreutils -- the small tools, as applets
;
; ## cu/base.x -- the tool chest, assembled
;
; @author [Jon Ruttan](jonruttan@gmail.com)
; @copyright 2026 Jon Ruttan
; @license MIT No Attribution (MIT-0)

(import cu/prims)

(provide cu/base cu-version cu-run cu-argv cu-main cu-sha256
  %cu-repl-print)

(def cu-version "0.1.0")

(def %cu-repl-print
  (fn (_ result)
    (unless (null? result) (write result))
    (newline)))

(include-once "./text.x")
(include-once "./trcut.x")
(include-once "./fs.x")
(include-once "./sha256.x")
(include-once "./hash.x")
(include-once "./sha512.x")
(include-once "./text3.x")
(include-once "./encode.x")
(include-once "./expr.x")
(include-once "./perm.x")
(include-once "./who.x")
(include-once "./text2.x")
(include-once "./fs2.x")
(include-once "./sys2.x")
(include-once "./test.x")
(include-once "./fs3.x")
(include-once "./ls.x")
(include-once "./sort.x")
(include-once "./text4.x")
(include-once "./walk.x")
(include-once "./fmt-lex.x")
(include-once "./date.x")
(include-once "./diff-lex.x")
(include-once "./diff.x")
(include-once "./find.x")
(include-once "./vi.x")
(include-once "./vi-move.x")
(include-once "./vi-edit.x")
(include-once "./vi-ex.x")
(include-once "./vi-set.x")
(include-once "./vi-undo.x")
(include-once "./more.x")
(include-once "./tsort.x")
(include-once "./strings.x")
(include-once "./cal.x")
(include-once "./net.x")
(include-once "./nc.x")
(include-once "./dns.x")
(include-once "./tftp.x")
(include-once "./ftp.x")
(include-once "./dump.x")
(include-once "./hexdump.x")
(include-once "./tree.x")
(include-once "./time.x")
(include-once "./base32.x")
(include-once "./ascii.x")
(include-once "./session.x")
(include-once "./httpd.x")
(include-once "./dnsd.x")
(include-once "./getopt.x")
(include-once "./runparts.x")
(include-once "./tar.x")
(include-once "./gzip.x")
(include-once "./procps.x")
(include-once "./options.x")
(include-once "./cli.x")
