; # x-coreutils -- the small tools, as applets
;
; ## tools/options-matrix.x -- the option matrix, generated
;
; @author [Jon Ruttan](jonruttan@gmail.com)
; @copyright 2026 Jon Ruttan
; @license MIT No Attribution (MIT-0)
;
; Applet parity was the first axis; OPTION parity is the second, and
; this is its scoreboard.  Busybox's side is docs/busybox-options.x
; (data, transcribed); ours is read LIVE from cu/cli.x's option
; DECLARATION -- the same row the guard checks and the applets read --
; so the matrix cannot drift from what the applets accept.
;
;   x -l coreutils -f tools/options-matrix.x > docs/options.md
;   make options

; busybox-options arrives by INCLUDE, not import, so no preload binds
; it -- this is the linter's own escape hatch for exactly that.
; lint-known: busybox-options
(include-once "docs/busybox-options.x")

(def %mx-member?
  (fn (self x xs)
    (if (null? xs) #f (if (string=? (first xs) x) #t (self x (rest xs))))))

(def %mx-minus
  (fn (_ xs ys) (filter (fn (_ x) (not (%mx-member? x ys))) xs)))

; SOME APPLETS TAKE NON-OPTION ARGUMENTS that busybox's usage text
; lists among the options: dd's operands are KEY=VALUE and never begin
; with a dash, so the option declaration cannot name them and the guard
; never sees them.  They are still accepted, so the matrix counts them
; -- from here, because there is nowhere else honest to read them from.
; the (NAME OPTIONS) shape %mx-lookup reads -- a pair here handed it a
; STRING where it wanted a list, and the append that followed
; SEGFAULTED rather than raising.
(def %mx-extra
  (list
    (list "dd" (list "if=" "of=" "bs=" "count=" "skip=" "seek=" "status="))))

(def %mx-lookup
  (fn (self name es)
    (if (null? es) (lit none)
      (if (string=? (first (first es)) name) (first (rest (first es)))
        (self name (rest es))))))

(def %mx-pct
  (fn (_ have want)
    (if (= want 0) "-"
      (string-append (%cu-int->str (/ (- (* have 100) (% (* have 100) want)) want)) "%"))))

(def %mx-cell
  (fn (_ xs) (if (null? xs) "" (%cu-join-with xs " "))))

(def %mx-names
  (%cu-msort (map (fn (_ e) (first e)) %cu-applets)
    (fn (_ a b) (%cu-str< a b))))

; one row: applet | busybox | ours | missing | coverage.  Answers the
; pair (have . want) so the totals fold over the same walk.
(def %mx-row
  (fn (_ name)
    (def bb (%mx-lookup name busybox-options))
    ; OURS COMES OFF THE DECLARATION cu/cli.x hands the guard and the
    ; applets alike -- both lists, since a value-taking flag is just as
    ; accepted as one that stands alone.
    (def spec (%cu-spec-of name))
    (def declared (if (null? spec) ()
                    (append (first spec) (first (rest spec)))))
    (def extra (let ((e (%mx-lookup name %mx-extra)))
                 (if (eq? e (lit none)) () e)))
    (def ours (append declared extra))
    (if (eq? bb (lit none))
      (do (display (string-concat
                     (list "| `" name "` | _not a busybox applet_ | "
                           (%mx-cell ours) " | | - |\n")))
          (pair 0 0))
      (let ((missing (%mx-minus bb ours)))
        (def have (- (length bb) (length missing)))
        (do (display
              (string-concat
                (list "| `" name "` | " (%mx-cell bb) " | " (%mx-cell ours)
                      " | " (%mx-cell missing) " | "
                      (%mx-pct have (length bb)) " |\n")))
            (pair have (length bb)))))))

(def %mx-main
  (fn (_)
    (display "# Option parity with busybox\n\n")
    (display "GENERATED by `make options` from `docs/busybox-options.x` (busybox 1.36's\n")
    (display "usage text, transcribed -- correct it against `busybox --help APPLET`)\n")
    (display "and the option guard's live table in `cu/cli.x`.  An option this bundle\n")
    (display "does not list is REFUSED, never silently ignored; the *missing* column is\n")
    (display "the work.  Applet parity is the other axis: see the README.\n\n")
    (display "| applet | busybox accepts | ours | missing | coverage |\n")
    (display "|---|---|---|---|---|\n")
    (def totals
      (let ((go (fn (self ns have want)
                  (if (null? ns) (pair have want)
                    (let ((r (%mx-row (first ns))))
                      (self (rest ns) (+ have (first r)) (+ want (rest r))))))))
        (go %mx-names 0 0)))
    (display
      (string-concat
        (list "\n**Total: " (%cu-int->str (first totals)) " of "
              (%cu-int->str (rest totals)) " busybox options accepted ("
              (%mx-pct (first totals) (rest totals)) ").**\n")))))

(%mx-main)
