; docs/busybox-options.x -- what busybox's coreutils applets ACCEPT.
;
; The data half of the option matrix (tools/options-matrix.x renders it
; against cu/cli.x's live option table).  Transcribed from busybox
; 1.36's usage text; a row here is a claim about busybox, so correct it
; against `busybox --help APPLET` rather than against this bundle.
; Single-letter flags are spelled as one string per applet; test's
; operators and dd's KEY=VALUE operands are listed whole.

(def %letters
  (fn (_ s)
    (def end (byte-len s))
    (def go (fn (self i acc)
              (if (>= i end) (reverse acc)
                (self (+ i 1)
                  (pair (string-append "-" (substring s i (+ i 1))) acc)))))
    (go 0 ())))

(def busybox-options
  (list
    (list "arch" ())
    (list "ascii" ())
    (list "base32" (%letters "diw"))
    (list "base64" (%letters "dw"))
    (list "basename" (%letters "s"))
    (list "cal" (%letters "jmy"))
    (list "cat" (%letters "nbvteA"))
    (list "chgrp" (%letters "RhLHPcvf"))
    (list "chmod" (%letters "Rcvf"))
    (list "chown" (%letters "RhLHPcvf"))
    (list "chroot" ())
    (list "cksum" ())
    (list "clear" ())
    (list "cmp" (%letters "lsn"))
    (list "comm" (%letters "123"))
    (list "cp" (%letters "arRPLHpfilsTu"))
    (list "cpio" (append (%letters "tiopHdmvuFRL0") (list "--ignore-devno" "--renumber-inodes")))
    (list "crc32" ())
    (list "cut" (%letters "bcfdsn"))
    (list "date" (append (%letters "udDsrRI") (list "+FMT")))
    (list "dd" (list "if=" "of=" "bs=" "ibs=" "obs=" "count=" "skip=" "seek="
                     "conv=" "status=" "iflag=" "oflag="))
    (list "df" (%letters "PkmhTaiB"))
    (list "diff" (%letters "abBdiNqrTstwLSU"))
    (list "dirname" ())
    (list "dos2unix" (%letters "ud"))
    (list "du" (%letters "aHLdclsxhmk"))
    (list "echo" (%letters "neE"))
    (list "env" (%letters "iu0"))
    (list "expand" (%letters "it"))
    (list "expr" ())
    (list "factor" ())
    (list "false" ())
    (list "flock" (%letters "sxun"))
    (list "fold" (%letters "bsw"))
    (list "free" (%letters "bkmgh"))
    (list "fsync" (%letters "d"))
    (list "getopt" (%letters "onqQsTual"))
    (list "groups" ())
    (list "gunzip" (%letters "cfkt"))
    (list "gzip" (%letters "cfkdt"))
    (list "hd" ())
    (list "head" (%letters "ncqv"))
    (list "hostid" ())
    (list "hostname" (%letters "sidfF"))
    (list "hexdump" (%letters "bcdoxCefnsv"))
    (list "id" (%letters "ugGnr"))
    (list "install" (%letters "cdDspogmt"))
    (list "link" ())
    (list "ln" (%letters "sfnbtv"))
    (list "logname" ())
    (list "ls" (%letters "1AaCxdLHRFplinshrSXvctuw"))
    (list "md5sum" (%letters "csw"))
    (list "mkdir" (%letters "mp"))
    (list "mesg" ())
    (list "mkfifo" (%letters "m"))
    (list "mknod" (%letters "m"))
    (list "mktemp" (%letters "dtpqu"))
    (list "more" (%letters "deflsu"))
    (list "mountpoint" (%letters "qdnx"))
    (list "mv" (%letters "finT"))
    (list "nice" (%letters "n"))
    (list "nl" (%letters "bnswvi"))
    (list "nohup" ())
    (list "nologin" ())
    (list "nproc" (list "--all" "--ignore=N"))
    (list "od" (%letters "AjNtvbcdox"))
    (list "paste" (%letters "ds"))
    (list "pgrep" (%letters "lafnovxsP"))
    (list "pidof" (%letters "so"))
    (list "printenv" ())
    (list "pipe_progress" ())
    (list "pkill" (%letters "lxfsPvnoe"))
    (list "printf" ())
    (list "ps" (%letters "oT"))
    (list "pwd" (%letters "LP"))
    (list "readlink" (%letters "fnv"))
    (list "realpath" ())
    (list "renice" (%letters "npgu"))
    (list "reset" ())
    (list "rev" ())
    (list "rm" (%letters "irRfv"))
    (list "rmdir" (%letters "p"))
    (list "run-parts" (list "-a" "-u" "--reverse" "--test" "--exit-on-error" "--list"))
    (list "seq" (%letters "ws"))
    (list "setsid" (%letters "c"))
    (list "sha1sum" (%letters "csw"))
    (list "sha256sum" (%letters "csw"))
    (list "sha384sum" (%letters "csw"))
    (list "sha512sum" (%letters "csw"))
    (list "shred" (%letters "fnuz"))
    (list "shuf" (%letters "einoz"))
    (list "sleep" ())
    (list "sort" (%letters "nrugMcszbdfiokt"))
    (list "split" (%letters "bla"))
    (list "stat" (%letters "Lftc"))
    (list "strings" (%letters "afont"))
    (list "sum" (%letters "rs"))
    (list "sync" (%letters "df"))
    (list "tac" ())
    (list "tail" (%letters "cfnqsv"))
    (list "tar" (list "-c" "-x" "-t" "-z" "-J" "-j" "-a" "-h" "-m" "-v" "-o" "-k" "-O" "-f" "-C"
                      "-T" "-X" "--lzma" "--exclude" "--overwrite" "--strip-components"
                      "--no-recursion" "--numeric-owner" "--no-same-permissions"
                      "--to-command"))
    (list "tee" (%letters "ai"))
    (list "test" (list "-e" "-f" "-d" "-s" "-z" "-n" "-r" "-w" "-x" "-L" "-h"
                       "-b" "-c" "-p" "-S" "-k" "-u" "-g" "-t"
                       "=" "!=" "-eq" "-ne" "-lt" "-le" "-gt" "-ge"
                       "-nt" "-ot" "-ef" "-a" "-o" "!" "(" ")"))
    (list "time" (%letters "vpafo"))
    (list "timeout" (%letters "sk"))
    (list "top" (%letters "bndmH"))
    (list "touch" (%letters "cdtr"))
    (list "tr" (%letters "cds"))
    (list "tree" ())
    (list "true" ())
    (list "truncate" (%letters "cs"))
    (list "ts" (%letters "is"))
    (list "tsort" ())
    (list "tty" (%letters "s"))
    (list "ttysize" ())
    (list "uname" (%letters "amnrspvio"))
    (list "unexpand" (%letters "fat"))
    (list "uniq" (%letters "cduifsw"))
    (list "unix2dos" (%letters "ud"))
    (list "unlink" ())
    (list "unzip" (%letters "lnojptqKxd"))
    (list "uptime" (%letters "s"))
    (list "users" ())
    (list "usleep" ())
    (list "uudecode" (%letters "o"))
    (list "uuencode" (%letters "m"))
    (list "uuidgen" (%letters "r"))
    (list "vi" (%letters "cRH"))
    (list "w" ())
    (list "wc" (%letters "cmlwL"))
    (list "wget" (append (%letters "cqSOoPYUTt")
                         (list "--spider" "--header" "--post-data" "--post-file"
                               "--no-check-certificate")))
    (list "nc" (%letters "elkpswinubvoz"))
    (list "nslookup" (list "-type" "-debug"))
    (list "tftp" (%letters "lrgpb"))
    (list "tftpd" (%letters "crlu"))
    (list "ftpget" (%letters "cvupP"))
    (list "ftpput" (%letters "cvupP"))
    (list "httpd" (%letters "cdhermupMKifv"))
    (list "dnsd" (%letters "dvsctpi"))
    (list "inetd" (%letters "feqR"))
    (list "tcpsvd" (%letters "hEvcCbul"))
    (list "udpsvd" (%letters "hEvcul"))
    (list "ftpd" (%letters "wAavStT"))
    (list "ipcalc" (%letters "bnmphs"))
    (list "which" (%letters "a"))
    (list "who" (%letters "aH"))
    (list "whois" (%letters "ihp"))
    (list "whoami" ())
    (list "xargs" (%letters "0aEInprstx"))
    (list "xxd" (%letters "lsapirgco"))
    (list "yes" ())
    (list "zcat" ())
    (list "[" (list "-e" "-f" "-d" "-s" "-z" "-n" "-r" "-w" "-x" "-L" "-h"
                    "-b" "-c" "-p" "-S" "-k" "-u" "-g" "-t"
                    "=" "!=" "-eq" "-ne" "-lt" "-le" "-gt" "-ge"
                    "-nt" "-ot" "-ef" "-a" "-o" "!" "(" ")"))
    (list "[[" (list "-e" "-f" "-d" "-s" "-z" "-n" "-r" "-w" "-x" "-L" "-h"
                     "-b" "-c" "-p" "-S" "-k" "-u" "-g" "-t"
                     "=" "!=" "-eq" "-ne" "-lt" "-le" "-gt" "-ge"
                     "-nt" "-ot" "-ef" "-a" "-o" "!" "(" ")"))))
